server:
  port: 8082
  
spring:
  data:
    mongodb:
      uri: mongodb+srv://mongodb:uwnvfDGYtNpC7gZU@collectbot-preprod.8ooov.mongodb.net/van_write
  jpa:
    show-sql: true
    
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG